baseURL = 'https://prachi25.github.io/myblog-hugo-/'
languageCode = 'en-us'
title = 'BLOGS'
theme = "ananke"
enableRobotsTXT = true

[params]
  description = "A blog about web development and technology."

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
